version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    # volumes:
    #   - mariadb:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge